# Generated by Django 4.2.5 on 2023-10-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="end_price",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
