# Generated by Django 4.2.5 on 2023-10-06 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auction", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="auctions", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
