# Generated by Django 4.2.5 on 2023-10-05 20:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0002_alter_auction_end_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auction",
            old_name="start_price",
            new_name="current_price",
        ),
    ]
