# Generated by Django 4.2.5 on 2023-10-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="txId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="auction",
            name="status",
            field=models.CharField(default="Active", max_length=10),
        ),
    ]
