# Generated by Django 4.2.5 on 2023-10-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0003_rename_start_price_auction_current_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(blank=True, default="image/auction/default.svg", null=True, upload_to="auction/"),
        ),
    ]
