# Generated by Django 4.2.5 on 2023-10-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auction", "0004_alter_auction_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="image",
            field=models.ImageField(
                blank=True, default="../static/images/auction/default.svg", null=True, upload_to="auction/"
            ),
        ),
    ]
