# Generated by Django 4.2.5 on 2023-10-06 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True, max_length=255)),
                (
                    "profile_image",
                    models.ImageField(default="../static/images/auction/default.svg", upload_to="profile/"),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")], max_length=50
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50)),
                ("phone_number", models.CharField(blank=True, max_length=12)),
                ("website_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profiles",
            },
        ),
    ]
