# Generated by Django 4.2.5 on 2023-10-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(default="../static/images/profile/default.svg", upload_to="profile/"),
        ),
    ]
